name: "Kernel crash dump"
stages:
  initramfs:
    - name: "enable kdump"
      if: 'grep -q root=LABEL=COS_ACTIVE /proc/cmdline && [ -n "$(blkid -L COS_ACTIVE)" ]'
      systemctl:
        enable:
          - kdump
