name: "Setup installer"
stages:
  initramfs:
    - commands:
      - setup-installer.sh
      # reference: https://github.com/harvester/harvester/issues/2663, thanks @Ernad's enhancement
      if: '! grep -q "harvester.installer.disable=true" /proc/cmdline'
    - environment_file: "/etc/rancher/installer/env"
      environment:
        HARVESTER_DASHBOARD: "true"
        KUBECONFIG: /etc/rancher/rke2/rke2.yaml
        PATH: /var/lib/rancher/rke2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      if: 'grep -q root=LABEL=COS_STATE /proc/cmdline && [ -n "$(blkid -L COS_STATE)" ]'
