linters:
  disable-all: true
  enable:
    - goimports
    - gofmt
    - misspell
    - revive
    - gosec
    - prealloc
issues:
  exclude-files:
    - /zz_generated_
    - _generated
  exclude-dirs:
    - generated
run:
  timeout: 5m
  tests: true
  build-tags:
    - test
linters-settings:
  gosec:
    # https://github.com/securego/gosec#available-rules
    excludes:
      - G101 # Look for hard coded credentials
      - G204 # Audit the use of command execution
      - G402 # TLS InsecureSkipVerify set true