apiVersion: v1
kind: Namespace
metadata:
  name: harvester-system
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: harvester
  namespace: kube-system
spec:
  bootstrap: true
  chart: https://localhost:9345/static/charts/$HARVESTER_CHART_TARBALL
  targetNamespace: harvester-system
  valuesContent: |-
    containers:
      apiserver:
        image:
          imagePullPolicy: "IfNotPresent"
        hciMode: true
    multus:
      enabled: false
    longhorn:
      enabled: true
      defaultSettings:
        taintToleration: "kubevirt.io/drain:NoSchedule"
    harvester-network-controller:
      enabled: true
      vipEnabled: true
      image:
        pullPolicy: "IfNotPresent"
    harvester-node-disk-manager:
      enabled: true
      image:
        pullPolicy: "IfNotPresent"
    rancherEmbedded: true
    webhook:
      image:
        imagePullPolicy: "IfNotPresent"
    harvester-load-balancer:
      enabled: true
    kube-vip:
      enabled: true
    kube-vip-cloud-provider:
      enabled: true
