apiVersion: v1
kind: Namespace
metadata:
  name: cattle-system
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rancher
  namespace: kube-system
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/$RANCHER_CHART
  targetNamespace: cattle-system
  set:
    ingress.enabled: "false"
    ingress.tls.source: "rancher"
    antiAffinity: "required"
    bootstrapPassword: "admin"
  valuesContent: |-
    extraEnv:
    - name: CATTLE_FEATURES
      value: multi-cluster-management=false,multi-cluster-management-agent=false
---
apiVersion: v1
kind: Service
metadata:
  name: rancher-expose
  namespace: cattle-system
spec:
  selector:
    app: rancher
  ports:
    - name: https-internal
      nodePort: 30443
      port: 443
      protocol: TCP
      targetPort: 444
  sessionAffinity: ClientIP
  type: NodePort
