apiVersion: v1
kind: Namespace
metadata:
  name: cattle-system
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rancher
  namespace: kube-system
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/$RANCHER_CHART
  targetNamespace: cattle-system
  set:
    ingress.enabled: "false"
    ingress.tls.source: "rancher"
    privateCA: "true"
    antiAffinity: "required"
    rancherImageTag: master-3e44415af2332fcc305cdb68907794d8b3b3e29a-head
---
apiVersion: v1
kind: Service
metadata:
  name: rancher-expose
  namespace: cattle-system
spec:
  selector:
    app: rancher
  ports:
    - name: https-internal
      nodePort: 30444
      port: 443
      protocol: TCP
      targetPort: 444
  sessionAffinity: ClientIP
  type: NodePort
