#!/bin/bash

source ../../scripts/k3os-version
if [ -z "$ARCH" ]; then
    ARCH=$(go env GOHOSTARCH)
fi

ARCH=${ARCH:-"amd64"}
TAG=${TAG:-"harvester-${HARVESTER_VERSION}-${ARCH}"}
REPO=${REPO:-rancher}

if echo "$TAG" | grep -q dirty; then
    TAG="harvester-dev"
fi
