#!/bin/bash

patch_rancher_monitoring_crd_chart()
{
  local chart_dir=$1 #${CHARTS_DIR}
  local monitoring_version=$2 #MONITORING_VERSION
  local pkg_monitoring_crd_path=$3 #${PKG_PATCH_MONITORING_PATH}
  local cwd=$(pwd)

  if [ ! -d "${pkg_monitoring_crd_path}/${monitoring_version}" ]; then
    echo "NOTE: there is no related path: ${pkg_monitoring_crd_path}/${monitoring_version} to patch, SKIP"
    return 0
  fi

  cd ${chart_dir}
  tar zxf rancher-monitoring-crd-${monitoring_version}.tgz --warning=no-timestamp

  # replace shell image version; yq can also work, but it strips all blank lines; use patch instead
  #  yq -e e '(.image | select(.repository == "rancher/shell") | .tag) = "v0.1.22"' -i ran-mon-crd-values.yaml
  local valuesfile="./rancher-monitoring-crd/values.yaml"
  local difffile="${pkg_monitoring_crd_path}/${monitoring_version}/patch-values-shell-version.diff"
  echo "patch rancher/shell image version"
  echo "the current values.yaml has following shell image version"
  grep "rancher/shell" $valuesfile -1 || true
  if [ -f "$difffile" ]; then
    patch $valuesfile $difffile
  else
    echo "diff file $difffile is not found"
  fi
  echo "the patched values.yaml has following shell image version"
  grep "rancher/shell" $valuesfile -1 || true

  # remove existing chart
  rm -f ${chart_dir}/rancher-monitoring-crd-${monitoring_version}.tgz

  # helm pack new
  helm package rancher-monitoring-crd
  rm -rf rancher-monitoring-crd
  echo "finish patch ranch-monitoring-crd chart"
  cd $cwd
}

