#!/bin/bash
set -e

cd $(dirname $0)/..

# duplicated from scripts/build, so that we can run `make test` standalone
addons_path=../addons
if [ ! -d ${addons_path} ];then
    echo "No existing addons source. Pulling..."
    git clone --branch v1.5 --single-branch --depth 1 https://github.com/harvester/addons.git ../addons
fi
cp ${addons_path}/pkg/templates/*.yaml ./pkg/config/templates

echo Running tests
go test -cover -tags=test ./pkg/...
