#!/usr/bin/env bash
set -euf -o pipefail

# TODO(kiefer): switch to wicked
exit 0

function usage()
{
    cat <<HELP
USAGE:
    harvester-configure-network INTERFACE dhcp
    harvester-configure-network INTERFACE static IP NETMASK GATEWAY NAMESERVERS
HELP
}

if [ $# -lt 2 ]; then
    usage
    exit 1
fi

INTERFACE=$1
MODE=$2
if [ "${MODE}" == "static" ]; then
  if [ $# -lt 6 ]; then
    usage
    exit 1
  fi
  IP=$3
  NETMASK=$4
  GATEWAY=$5
  shift 5
  NAMESERVERS=$*
fi

function write_log()
{
    local message="${1}"
    logger -t "harvester-configure-network" "${message}"
    echo "${message}"
}

function configure_network()
{
    local service
    service=$(connmanctl services | awk '{ print $3 }' | while read -r s; do if connmanctl services "${s}" | grep -q "${INTERFACE}"; then echo "${s}"; fi; done)
    test -n "${service}"
    if [ "${MODE}" == "static" ]; then
      write_log "Config ipv4 static ${INTERFACE}(${service}): address ${IP} mask ${NETMASK} gw ${GATEWAY} nameservers ${NAMESERVERS}"
      connmanctl config "${service}" --ipv4 manual "${IP}" "${NETMASK}" "${GATEWAY}" --nameservers ${NAMESERVERS}
    else
      write_log "Config ipv4 dhcp ${INTERFACE}(${service})"
      connmanctl config "${service}" --ipv4 dhcp
    fi
}

configure_network
