resources:
  - apiVersion: management.cattle.io/v3
    kind: ManagedChart
    metadata:
      name: harvester-logging
      namespace: fleet-local
    spec:
      chart: harvester-logging
      releaseName: harvester-logging
      version: {{ .MonitoringChartVersion }}
      defaultNamespace: cattle-monitoring-system
      repoName: harvester-charts
      diff:
        comparePatches:
          - apiVersion: admissionregistration.k8s.io/v1
            kind: ValidatingWebhookConfiguration
            name: harvester-logging-admission
            operations:
              - { "op": "remove", "path": "/webhooks" }
          - apiVersion: admissionregistration.k8s.io/v1
            kind: MutatingWebhookConfiguration
            name: harvester-logging-admission
            operations:
              - { "op": "remove", "path": "/webhooks" }
      targets:
        - clusterName: local
          clusterSelector:
            matchExpressions:
              - key: provisioning.cattle.io/unmanaged-system-agent
                operator: DoesNotExist
      values:
        alertmanager:
          enabled: false
        grafana:
          persistence:
            enabled: true
            size: "10"
            storageClassName: longhorn
            type: pvc
            accessModes:
              - ReadWriteOnce
        prometheus:
          prometheusSpec:
            evaluationInterval: 1m
            resources:
              limits:
                cpu: 1000m
                memory: 2500Mi
              requests:
                cpu: 750m
                memory: 1750Mi
            retention: 5d
            retentionSize: 50GiB
            scrapeInterval: 1m
            storageSpec:
              volumeClaimTemplate:
                spec:
                  accessModes:
                    - ReadWriteOnce
                  resources:
                    requests:
                      storage: 50Gi
                  storageClassName: longhorn
                  volumeMode: Filesystem
        prometheus-node-exporter:
          resources:
            limits:
              cpu: 200m
              memory: 180Mi
            requests:
              cpu: 100m
              memory: 30Mi
