resources:
- apiVersion: management.cattle.io/v3
  kind: ManagedChart
  metadata:
    name: rancher-logging
    namespace: fleet-local
  spec:
    chart: rancher-logging
    releaseName: rancher-logging
    version: {{ .LoggingChartVersion }}
    defaultNamespace: cattle-logging-system
    repoName: harvester-charts
    targets:
      - clusterName: local
        clusterSelector:
          matchExpressions:
            - key: provisioning.cattle.io/unmanaged-system-agent
              operator: DoesNotExist
    values:
      fluentd:
        resources:
          limits:
            cpu: 1000m
            memory: 800Mi
          requests:
            cpu: 100m
            memory: 200Mi
      fluentbit:
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 50Mi
- apiVersion: logging.banzaicloud.io/v1beta1
  kind: ClusterFlow
  metadata:
    name: harvester-loki
    namespace: cattle-logging-system
  spec:
    match:
      - select: { }
    globalOutputRefs:
      - harvester-loki
- apiVersion: logging.banzaicloud.io/v1beta1
  kind: ClusterOutput
  metadata:
    name: harvester-loki
    namespace: cattle-logging-system
  spec:
    loki:
      url: http://loki-stack.cattle-logging-system.svc:3100
      extra_labels:
        logOutput: harvester-loki
