resources:
- apiVersion: management.cattle.io/v3
  kind: ManagedChart
  metadata:
    name: kubeovn-operator-crd
    namespace: fleet-local
  spec:
    chart: kubeovn-operator-crd
    releaseName: kubeovn-operator-crd
    version: {{ .KubeovnOperatorChartVersion }}
    defaultNamespace: kube-system
    repoName: harvester-charts
    timeoutSeconds: 600
    targets:
    - clusterName: local
      clusterSelector:
        matchExpressions:
        - key: provisioning.cattle.io/unmanaged-system-agent
          operator: DoesNotExist
