resources:
- apiVersion: management.cattle.io/v3
  kind: ManagedChart
  metadata:
    name: rancher-logging
    namespace: fleet-local
  spec:
    chart: rancher-logging
    releaseName: rancher-logging
    version: {{ .LoggingChartVersion }}
    defaultNamespace: cattle-logging-system
    repoName: harvester-charts
    diff:
      comparePatches:
        - apiVersion: admissionregistration.k8s.io/v1
          kind: ValidatingWebhookConfiguration
          name: rancher-logging-admission
          operations:
            - { "op": "remove", "path": "/webhooks" }
        - apiVersion: admissionregistration.k8s.io/v1
          kind: MutatingWebhookConfiguration
          name: rancher-logging-admission
          operations:
            - { "op": "remove", "path": "/webhooks" }
    targets:
      - clusterName: local
        clusterSelector:
          matchExpressions:
            - key: provisioning.cattle.io/unmanaged-system-agent
              operator: DoesNotExist
- apiVersion: logging.banzaicloud.io/v1beta1
  kind: ClusterFlow
  metadata:
    name: harvester-loki
    namespace: cattle-logging-system
  spec:
    match:
      - select: { }
    globalOutputRefs:
      - harvester-loki
- apiVersion: logging.banzaicloud.io/v1beta1
  kind: ClusterOutput
  metadata:
    name: harvester-loki
    namespace: cattle-logging-system
  spec:
    loki:
      url: http://loki-stack.cattle-logging-system.svc:3100
      extra_labels:
        logOutput: harvester-loki
