resources:
- apiVersion: management.cattle.io/v3
  kind: ManagedChart
  metadata:
    name: harvester-journal
    namespace: fleet-local
  spec:
    chart: harvester-journal
    releaseName: harvester-journal
    version: {{ .LoggingChartVersion }}
    repoName: harvester-charts
    defaultNamespace: cattle-logging-system
    targets:
      - clusterName: local
        clusterSelector:
          matchExpressions:
            - key: provisioning.cattle.io/unmanaged-system-agent
              operator: DoesNotExist
    values:
      debug: true
      systemdLogPath: "/var/log/journal"