resources: {{ if not .ClusterNetworks -}} [] {{- else }}
{{- range $name, $network := .ClusterNetworks }}
- apiVersion: network.harvesterhci.io/v1beta1
  kind: ClusterNetwork
  metadata:
    name: {{ printf "%q" $name }}
{{- with $network }}
  enable: {{ if .Enable }} true {{- else }} false {{- end }}
{{- if .Description }}
  description: {{ printf "%q" .Description }}
{{- end }}
{{- if .Config }}
  config:
{{- range $name, $value := .Config }}
    {{ $name }}: {{ $value }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end -}}
