resources:
- apiVersion: management.cattle.io/v3
  kind: ManagedChart
  metadata:
    name: rancher-logging
    namespace: fleet-local
  spec:
    chart: rancher-logging
    releaseName: rancher-logging
    version: {{ .LoggingChartVersion }}
    defaultNamespace: cattle-logging-system
    repoName: harvester-charts
    targets:
    - clusterName: local
      clusterSelector:
        matchExpressions:
        - key: provisioning.cattle.io/unmanaged-system-agent
          operator: DoesNotExist
    values:
      images:
        fluentbit:
          tag: 1.9.5 # replace the default 1.9.3, which has bug in systemd log
        fluentbit_debug:
          tag: 1.9.5-debug
      systemdLogPath: /var/log/journal
      disablePvc: true
      additionalLoggingSources:
        rke2:
          enabled: true
        kubeAudit:
          enabled: true
          auditFilename: "audit.log"
          pathPrefix: "/var/lib/rancher/rke2/server/logs/"
          loggingRef: "harvester-kube-audit-log-ref"
          fluentbit:
            logTag: kube-audit
            tolerations:
            - key: node-role.kubernetes.io/controlplane
              value: "true"
              effect: NoSchedule
            - key: node-role.kubernetes.io/etcd
              value: "true"
              effect: NoExecute
      fluentd:
        resources:
          limits:
            cpu: 1000m
            memory: 800Mi
          requests:
            cpu: 100m
            memory: 200Mi
      fluentbit:
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 50Mi
- apiVersion: logging-extensions.banzaicloud.io/v1alpha1
  kind: EventTailer
  metadata:
    name: harvester-default
    namespace: cattle-logging-system
  spec:
    controlNamespace: cattle-logging-system
    # https://banzaicloud.com/docs/one-eye/logging-operator/configuration/extensions/kubernetes-event-tailer/
    # workloadOverrides *types.PodSpecBase
    workloadOverrides:
      containers:
      - image: banzaicloud/eventrouter:v0.1.0
        name: event-tailer
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 20m
            memory: 20Mi
