#!/bin/bash

LINKFLAGS=${LINKFLAGS:-"-extldflags -static -s"}
exec env CGO_ENABLED=0 go build -ldflags \
"-X github.com/rancher/k3os/pkg/version.Version=$VERSION
-X github.com/rancher/k3os/vendor/github.com/rancher/harvester-installer/pkg/version.Version=$HARVESTER_VERSION
$LINKFLAGS" "$@"
